apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-delivery"
spec:
  stages:
    - name: "build-in-develop"
      sequences:
        - name: "delivery"
          tasks:
            - name: "deployment"
            - name: "test"

    - name: "r4-deploy"
      sequences:
        - name: "delivery"
          triggeredOn:
            - event: "build-in-develop.delivery.finished"
          tasks:
            - name: "deployment"
            - name: "test"
    - name: "create-release-branch"
      sequences:
        - name: "delivery"
          triggeredOn:
            - event: "r4-deploy.delivery.finished"
          tasks:
            - name: "approval"
              properties:
                pass: "manual"
                warning: "manual"
            - name: "deployment"
